<?php

namespace GestionBudgetBundle\Repository;

/**
 * DonneesBudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesBudgetRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllDonneesBudgetByUserCommune($usercommune) {

        $query = $this->createQueryBuilder('db')
            ->join('db.commune','com')
            ->where('com.nomCommune = :usercommune')
            ->setParameter('usercommune', $usercommune)
            ->getQuery();
        $donnees = $query->getResult();
        return $donnees;

    }
    public function getAllDonneesBudgetByUserDeparttement($userdepart) {

        $query = $this->createQueryBuilder('db')
            ->join('db.departement','dep')
            ->where('dep.nomDepartement = :userdepart')
            ->setParameter('userdepart', $userdepart)
            ->getQuery();
        $donnees = $query->getResult();
        return $donnees;

    }
}
