<?php

namespace GestionBudgetBundle\Repository;

/**
 * DonneesBudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesBudgetRepository extends \Doctrine\ORM\EntityRepository
{
}
