<?php

namespace GestionBudgetBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDepartementsByCode($code) {

        $query = $this->createQueryBuilder('r')
            ->select('r.departements')
            ->where('r.id='.$code)
            ->getQuery();
        $donnees = $query->getResult();
        return $donnees;
    }
}
