<?php

namespace GestionBudgetBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDepartementsByCode($code) {

        $query = $this->createQueryBuilder('r')
            ->select('r.departements')
            ->where('r.id='.$code)
            ->getQuery();
        $donnees = $query->getResult();
        return $donnees;
    }
    public function getNomRegionByCode($code) {
        $query = $this->createQueryBuilder('region')
                ->select('region.nomRegion')
                ->where('region.codeRegion=:code')
                ->setParameter('code',$code)
                ->getQuery();

        return $query->getSingleResult();
    }
}
