fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
gestion_budget_axe:
    resource: "@GestionBudgetBundle/Controller/AxeController.php"
    type:     annotation

gestion_budget:
    resource: "@GestionBudgetBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_group_delete:
    prefix: /user
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"

